#!/usr/bin/env python

# To print a number in its binary representation, we use
# bin(int) function
print bin(1) # = '0b1'

# We can do the same for octal and hexadecimal
#
print 'octal: ' + oct(1)
print 'hexadecimal: ' + hex(1)

# The int function can be used to convert a nondecimal
# number to a decimal number. Give int() a second argument
# that is the base of the first argument number system
#
print int('1010', 2) # converts 0b1010 to 10

# The bitwise shift operators are << and >>, left-shift and right-shift
#
print bin(0b1110 << 2)
print bin(0b1000 >> 2)

# The bitwise logic operators are 
# &(AND), |(OR), ~(NOT), ^(XOR)


