#!/usr/bin/env python

# Function to count number of an item within a list
#
def count(seq, item):
    # Initialize total
    #
    total = 0
    # Loop through sequence
    #
    for x in seq:
        # If current item is a match
        #
        if (x == item):
            # Add to total
            #
            total += 1
    return total

# Ask for list and item
#
sequence = raw_input('List> ')
item = raw_input('Item> ')

sequence = sequence.split(',')
print sequence

# Compute the count of items in list
#
num = count(sequence, item)

print num
print type(item)
