#!/usr/bin/env python

# generic import
#
import math
# math.sqrt(25) = 5

# Function import
#
from math import sqrt
# sqrt(25) = 5

# Univversal import
#
from math import *
# sqrt(25) = 5 # HUGE memory request. Unable to tell function origin

# this is a function defintion
#
def add_two(num):
    num += 2
    return num

num = raw_input("add two to this number: ")
print add_two(num)

# Take all the arguments given to a function and make into a (list/string)?
#
def mega(*args):
    # print max number
    print max(args)

mega(1,2,3,4,5,6)
