#!/usr/bin/env python

# Request a string from user
#
s = raw_input('Please provide a string: ')

# Reverse the order of string s and store in list y
#
def reverse(x):
    y = []
    for i in range(1,len(x)+1):
        y.append( x[len(x) - i] )

    # Join the list y with '' (nothing) and cast as string ss
    #
    y = str( ''.join(y) )
    return y

# Call reversal function on string s
ss = reverse(s)

# Print new string ss which is s reversed
#
print 'Did you mean \'%s\' ?' % (ss)

print type(ss)
