#!/usr/bin/env python

# Dictionary defining score for scrabble letters
#
score = {"a": 1, "c": 3, "b": 3, "e": 1, "d": 2, "g": 2, 
         "f": 4, "i": 1, "h": 4, "k": 5, "j": 8, "m": 3, 
         "l": 1, "o": 1, "n": 1, "q": 10, "p": 3, "s": 1, 
         "r": 1, "u": 1, "t": 1, "w": 4, "v": 4, "y": 4, 
         "x": 8, "z": 10}

# Function takes word string and determines score
#
def scrabble_score(word):
    total = 0
    # Make word lowercase
    #
    word = word.lower()
    # loop overr the length of the word
    #
    for c in word:
        # Determine the score per char
        #
        letter_score = score[c]
        # Add to total
        #
        total += letter_score
    return total
    

# Read the input string
#
word = raw_input('Spell a word: ')

# Score the word
#
word_score = scrabble_score(word)

print 'Word score: %d' % word_score
